### ISSUE TITLE
Document data_provider decorator

### ISSUE THREAD

**Issue by lnajman** [higra/Higra#114]
We can write things like
cs = hg.attribute_perimeter_length(t1, vertex_perimeter=vertex_contour_weight,  frontier_length=frontier_sum, no_cache=True)
but as far as I know, there is no documentation for that.

**Comment by PerretB** [comment]
Yes, the ``data_provider`` decorator which provides homogeneous caching strategy has to be documented. However, I first  would like to improve it to have a more natural behavior. 

Currently, the caching mechanism discards all function parameters except the first one and uses the id of this first argument to determine if the result of the function has already been computed. In order to  be fully transparent it should verify that all parameters  are equal to the one of a previous call in order to determine if it can use a cached result. As this can quickly become time consuming, I think that an intermediate strategy considering only the id (and the hash if id is not available) of the parameters could be sufficient.
