### ISSUE TITLE
pip installation failed

### ISSUE THREAD

**Issue by hugoverzone** [higra/Higra#274]
Hello!
I'm unable to install higra with PIP.
when running the usual commands, such as: $pip install higra
I get:
ERROR: Could not find a version that satisfies the requirement higra (from versions: none)
ERROR: No matching distribution found for higra

when running commands such as: $ pip index versions higra
to see what versions are available,

WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
ERROR: No matching distribution found for higra

Is higra still available through pip?
Is there an issue with my setup?

I'm on a 2021 m1 macbook pro
running the commands in a VSCode terminal
in a conda environment

**Comment by PerretB** [comment]
Hello! 

Yes, Higra is still distributed on Pip, but unfortunately Mac silicon (m1, m2, m3) is not yet supported (see issue #249).
In short, the problem is that Azure pipelines (and other free CI/CD pipelines) do not have mac silicon agent to build the package on this hardware.

So currently you have two options to use Higra on a Mac m1: either compile it yourself (see [manual build](https://higra.readthedocs.io/en/stable/install.html#manual-build)) or use an x86 version of Python with Rosetta
